### PR TITLE
Work with relative paths

### LINKED ISSUE #825: Cannot find path "output"
When running `vendor/bin/guides -vvv --no-progress -- docs/en`,  I get 

```
$ vendor/bin/guides -vvv --no-progress -- docs/en

In Run.php line 372:

  [RuntimeException]
  Cannot find path "output".


Exception trace:
  at /home/greg/dev/doctrine-orm/minor/vendor/phpdocumentor/guides-cli/src/Command/Run.php:372
 phpDocumentor\Guides\Cli\Command\Run->getAbsolutePath() at /home/greg/dev/doctrine-orm/minor/vendor/phpdocumentor/guides-cli/src/Command/Run.php:275
 phpDocumentor\Guides\Cli\Command\Run->execute() at /home/greg/dev/doctrine-orm/minor/vendor/symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at /home/greg/dev/doctrine-orm/minor/vendor/symfony/console/Application.php:1049
 Symfony\Component\Console\Application->doRunCommand() at /home/greg/dev/doctrine-orm/minor/vendor/symfony/console/Application.php:318
 Symfony\Component\Console\Application->doRun() at /home/greg/dev/doctrine-orm/minor/vendor/symfony/console/Application.php:169
 Symfony\Component\Console\Application->run() at /home/greg/dev/doctrine-orm/minor/vendor/phpdocumentor/guides-cli/bin/guides:66
 include() at /home/greg/dev/doctrine-orm/minor/vendor/bin/guides:119
```

This is confusing because I never specified `output` anywhere.

### PR DESCRIPTION
**Pull request by greg0ire**
`getAbsolutePath()` was introduced in #284, but it is unclear to me why. Removing it seems to fix UX inconsistencies without introducing other issues.

It causes non-existent relative paths to be treated differently than non-existent absolute paths: using the former crashes the program, while using the latter results in directories being created at the provided paths.

Closes #825

### CODE REVIEW

**Comment by linawolf** [comment]
I think we needed to introduce this for usage inside of docker. I dont really remember why we introduced it though

File: packages/guides-cli/src/Command/Run.php [hunk 1]
```diff
@@ -261,7 +258,7 @@ private function getSettingsOverriddenWithInput(InputInterface $input): ProjectS
     protected function execute(InputInterface $input, OutputInterface $output): int
     {
         $settings = $this->getSettingsOverriddenWithInput($input);
-        $inputDir = $this->getAbsolutePath($settings->getInput());
```
Comment (jaapio) [inline packages/guides-cli/src/Command/Run.php:264]: I think we should keep this, line, we want to break when input is not an existing directory.

File: packages/guides-cli/src/Command/Run.php [hunk 2]
```diff
@@ -281,7 +278,7 @@ protected function execute(InputInterface $input, OutputInterface $output): int
         $projectNode = $event->getProjectNode();
         $settings = $event->getSettings();
 
-        $outputDir = $this->getAbsolutePath($settings->getOutput());
+        $outputDir = $settings->getOutput();
```
Comment (jaapio) [inline packages/guides-cli/src/Command/Run.php:281]: :+1:

**Review by jaapio — CHANGES_REQUESTED** [review]
I think we should just change the output directory handling. Not the input, as the issue was just focusing on output.

File: packages/guides-cli/src/Command/Run.php (hunk 1 above)
Comment (jaapio) [reply packages/guides-cli/src/Command/Run.php:264]: Except that the getAbsolutePath did convert it to a real path, relative to the current working directory, I think that's an important difference.

Comment (greg0ire) [reply packages/guides-cli/src/Command/Run.php:264]: > Except that the getAbsolutePath did convert it to a real path
yes

> relative to the current working directory

Uuuuuh… no? :sweat_smile: I mean it's called `getAbsolutePath`, so, it produced absolute paths. 



Anyway, in the rest of the method `$inputDir` unused from these 3 lines:

```php
        if (!is_dir($inputDir)) {
            throw new RuntimeException(sprintf('Input directory "%s" was not found! ' . "\n" .
                'Run "vendor/bin/guides -h" for information on how to configure this command.', $inputDir));
        }
```

So the only difference it makes is in the error message of that exception. Is it important to have an absolute path in that message?

**Review by jaapio — APPROVED** [review]
